### PR TITLE
Package protocol headers

### PR DESCRIPTION
**Pull request by m-col**
This lets libraries that depend on pywlroots have access to the headers,
which is required if they need to compile their own CFFI module using
wlroots' CFFI.

### CODE REVIEW

**Review by flacjacket — COMMENTED** [review]
Can we then remove the files in `include/`?

**Comment by m-col** [comment]
Huh, thought I had done that. Yep.

**Comment by m-col** [comment]
Just updated the manifest as the syntax was a bit wrong but it's corrected now.

**Comment by flacjacket** [comment]
Thanks!

**Pull request merged**
